name: SecretHitler
version: 0
author: RobFro
main: de.robfro.secrethitler.Main

commands:
  test:
    usage: '/<command>'
  room:
    usage: '/<command> create|cr|spawn|itemFrame|if|electionTracker|et  NAME'
  dummy:
    usage: '/<command> [ID|NAME]'
    aliases: [d]
  chgnm:
    usage: '/<command>'
  wait:
    usage: '/<command> SEC'
  nominate:
    usage: '/<command> NAME'